const ANALYTICS_REQUEST = 'ANALYTICS_REQUEST';
const ANALYTICS_REQUEST_SUCCESS = 'ANALYTICS_REQUEST_SUCCESS';
const ANALYTICS_REQUEST_FAIL = 'ANALYTICS_REQUEST_FAIL';
const ANALYTICS_RESET = 'ANALYTICS_RESET';

export { ANALYTICS_REQUEST, ANALYTICS_REQUEST_SUCCESS, ANALYTICS_REQUEST_FAIL, ANALYTICS_RESET };
