const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';
const AUTH_REGISTER_RESET = 'AUTH_REGISTER_RESET';

const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
const AUTH_LOGOUT = 'AUTH_LOGOUT';

const AUTH_PROFILE_REQUEST = 'AUTH_PROFILE_REQUEST';
const AUTH_PROFILE_SUCCESS = 'AUTH_PROFILE_SUCCESS';
const AUTH_PROFILE_FAIL = 'AUTH_PROFILE_FAIL';

const AUTH_UPDATE_PROFILE_REQUEST = 'AUTH_UPDATE_PROFILE_REQUEST';
const AUTH_UPDATE_PROFILE_SUCCESS = 'AUTH_UPDATE_PROFILE_SUCCESS';
const AUTH_UPDATE_PROFILE_FAIL = 'AUTH_UPDATE_PROFILE_FAIL';
const AUTH_UPDATE_PROFILE_RESET = 'AUTH_UPDATE_PROFILE_RESET';

const AUTH_UPDATE_PASSWORD_REQUEST = 'AUTH_UPDATE_PASSWORD_REQUEST';
const AUTH_UPDATE_PASSWORD_SUCCESS = 'AUTH_UPDATE_PASSWORD_SUCCESS';
const AUTH_UPDATE_PASSWORD_FAIL = 'AUTH_UPDATE_PASSWORD_FAIL';
const AUTH_UPDATE_PASSWORD_RESET = 'AUTH_UPDATE_PASSWORD_RESET';

const AUTH_FORGOT_PASSWORD_REQUEST = 'AUTH_FORGOT_PASSWORD_REQUEST';
const AUTH_FORGOT_PASSWORD_SUCCESS = 'AUTH_FORGOT_PASSWORD_SUCCESS';
const AUTH_FORGOT_PASSWORD_FAIL = 'AUTH_FORGOT_PASSWORD_FAIL';
const AUTH_FORGOT_PASSWORD_RESET = 'AUTH_AUTH_FORGOT_PASSWORD_RESET';

export {
  AUTH_LOGIN_REQUEST,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAIL,
  AUTH_LOGOUT,
  AUTH_REGISTER_REQUEST,
  AUTH_REGISTER_SUCCESS,
  AUTH_REGISTER_FAIL,
  AUTH_REGISTER_RESET,
  AUTH_PROFILE_REQUEST,
  AUTH_PROFILE_SUCCESS,
  AUTH_PROFILE_FAIL,
  AUTH_UPDATE_PROFILE_REQUEST,
  AUTH_UPDATE_PROFILE_SUCCESS,
  AUTH_UPDATE_PROFILE_FAIL,
  AUTH_UPDATE_PROFILE_RESET,
  AUTH_UPDATE_PASSWORD_REQUEST,
  AUTH_UPDATE_PASSWORD_SUCCESS,
  AUTH_UPDATE_PASSWORD_FAIL,
  AUTH_UPDATE_PASSWORD_RESET,
  AUTH_FORGOT_PASSWORD_REQUEST,
  AUTH_FORGOT_PASSWORD_SUCCESS,
  AUTH_FORGOT_PASSWORD_FAIL,
  AUTH_FORGOT_PASSWORD_RESET,
};
