const FUNDRAISER_CREATE_REQUEST = 'FUNDRAISER_CREATE_REQUEST';
const FUNDRAISER_CREATE_SUCCESS = 'FUNDRAISER_CREATE_SUCCESS';
const FUNDRAISER_CREATE_FAIL = 'FUNDRAISER_CREATE_FAIL';
const FUNDRAISER_CREATE_RESET = 'FUNDRAISER_CREATE_RESET';

const FUNDRAISER_DELETE_REQUEST = 'FUNDRAISER_DELETE_REQUEST';
const FUNDRAISER_DELETE_SUCCESS = 'FUNDRAISER_DELETE_SUCCESS';
const FUNDRAISER_DELETE_FAIL = 'FUNDRAISER_DELETE_FAIL';
const FUNDRAISER_DELETE_RESET = 'FUNDRAISER_DELETE_RESET';

const FUNDRAISER_UPDATE_REQUEST = 'FUNDRAISER_UPDATE_REQUEST';
const FUNDRAISER_UPDATE_SUCCESS = 'FUNDRAISER_UPDATE_SUCCESS';
const FUNDRAISER_UPDATE_FAIL = 'FUNDRAISER_UPDATE_FAIL';
const FUNDRAISER_UPDATE_RESET = 'FUNDRAISER_UPDATE_RESET';

const TOP_THREE_FUNDRAISER_REQUEST = 'TOP_THREE_FUNDRAISER_REQUEST';
const TOP_THREE_FUNDRAISER_SUCCESS = 'TOP_THREE_FUNDRAISER_SUCCESS';
const TOP_THREE_FUNDRAISER_FAIL = 'TOP_THREE_FUNDRAISER_FAIL';

const FUNDRAISER_LIST_REQUEST = 'FUNDRAISER_LIST_REQUEST';
const FUNDRAISER_LIST_SUCCESS = 'FUNDRAISER_LIST_SUCCESS';
const FUNDRAISER_LIST_FAIL = 'FUNDRAISER_LIST_FAIL';

const FUNDRAISER_DETAILS_REQUEST = 'FUNDRAISER_DETAILS_REQUEST';
const FUNDRAISER_DETAILS_SUCCESS = 'FUNDRAISER_DETAILS_SUCCESS';
const FUNDRAISER_DETAILS_FAIL = 'FUNDRAISER_DETAILS_FAIL';

export {
  FUNDRAISER_CREATE_REQUEST,
  FUNDRAISER_CREATE_SUCCESS,
  FUNDRAISER_CREATE_FAIL,
  FUNDRAISER_CREATE_RESET,
  FUNDRAISER_LIST_REQUEST,
  FUNDRAISER_LIST_SUCCESS,
  FUNDRAISER_LIST_FAIL,
  FUNDRAISER_DELETE_REQUEST,
  FUNDRAISER_DELETE_SUCCESS,
  FUNDRAISER_DELETE_FAIL,
  FUNDRAISER_DELETE_RESET,
  FUNDRAISER_UPDATE_REQUEST,
  FUNDRAISER_UPDATE_SUCCESS,
  FUNDRAISER_UPDATE_FAIL,
  FUNDRAISER_UPDATE_RESET,
  TOP_THREE_FUNDRAISER_REQUEST,
  TOP_THREE_FUNDRAISER_SUCCESS,
  TOP_THREE_FUNDRAISER_FAIL,
  FUNDRAISER_DETAILS_REQUEST,
  FUNDRAISER_DETAILS_SUCCESS,
  FUNDRAISER_DETAILS_FAIL,
};
