const FUNDRAISER_LIST_REQUEST = 'FUNDRAISER_LIST_REQUEST';
const FUNDRAISER_LIST_SUCCESS = 'FUNDRAISER_LIST_SUCCESS';
const FUNDRAISER_LIST_FAIL = 'FUNDRAISER_LIST_FAIL';

const FUNDRAISER_DETAILS_REQUEST = 'FUNDRAISER_DETAILS_REQUEST';
const FUNDRAISER_DETAILS_SUCCESS = 'FUNDRAISER_DETAILS_SUCCESS';
const FUNDRAISER_DETAILS_FAIL = 'FUNDRAISER_DETAILS_FAIL';

export {
  FUNDRAISER_LIST_REQUEST,
  FUNDRAISER_LIST_SUCCESS,
  FUNDRAISER_LIST_FAIL,
  FUNDRAISER_DETAILS_REQUEST,
  FUNDRAISER_DETAILS_SUCCESS,
  FUNDRAISER_DETAILS_FAIL,
};
