const USER_GET_REQUEST = 'USER_GET_REQUEST';
const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
const USER_GET_FAIL = 'USER_GET_FAIL';
const USER_GET_RESET = 'USER_GET_RESET';

const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
const USER_LIST_FAIL = 'USER_LIST_FAIL';
const USER_LIST_RESET = 'USER_LIST_RESET';

const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
const USER_DELETE_RESET = 'USER_DELETE_RESET';

export {
  USER_GET_REQUEST,
  USER_GET_SUCCESS,
  USER_GET_FAIL,
  USER_GET_RESET,
  USER_LIST_REQUEST,
  USER_LIST_SUCCESS,
  USER_LIST_FAIL,
  USER_LIST_RESET,
  USER_UPDATE_REQUEST,
  USER_UPDATE_SUCCESS,
  USER_UPDATE_FAIL,
  USER_UPDATE_RESET,
  USER_DELETE_REQUEST,
  USER_DELETE_SUCCESS,
  USER_DELETE_FAIL,
  USER_DELETE_RESET,
};
